apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mariadb:latest
          ports:
          - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mariadb
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-data       
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: mysql-data
        hostPath:
          path: /data/mariadb/data
          type: Directory            